name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      # build docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          target-folder: docs/dev # the folder in gh-pages that will be created/cleaned
          clean: true # Automatically remove deleted files from the deploy branch

      #- name: Deploy
      #  uses: JamesIves/github-pages-deploy-action@4.0.0
      #  with:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    branch: gh-pages # The branch the action should deploy to.
      #    folder: docs # The folder the action should deploy.
      #    target-folder: docs/latest # the folder in gh-pages that will be created/cleaned
      #    clean: true # Automatically remove deleted files from the deploy branch

      - name: Find current tag
        run: echo "tag=$(git tag --points-at HEAD)" >> $GITHUB_ENV

      - run: echo "${{ env.tag }}"

      - if: ${{ startsWith(env.tag, 'v') }}
        run: echo "VERSION!!!"
